spring.application.name=savatteri-euris
server.port=8080
server.servlet.context-path=/se

#Database
spring.datasource.url=jdbc:sqlserver://127.0.0.1:1433;databaseName=SavatteriEurisDev;encrypt=true;trustServerCertificate=true
spring.datasource.username=euris_user
spring.datasource.password=1234
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

#Jobs
queue.QueueProductModifiedConsumer.enabled=true
queue.QueueOrdersModifiedConsumer.enabled=true

#Swagger
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui/index.html