spring.application.name=savatteri-euris

spring.datasource.url=jdbc:sqlserver://(localdb)\\MSSQLLocalDB;databaseName=SavatteriEurisDev;integratedSecurity=true;trustServerCertificate=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true